<?php

namespace Database\Seeders;


use Devlab\ShopifyApiLaravel\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();

        $records = [
            ['id' => 1, 'name' => json_encode(['es' => 'Afganistán', 'en' => 'Afghanistan']), 'iso2' => 'AF', 'iso3' => 'AF', 'phone_code' => ''],
            ['id' => 2, 'name' => json_encode(['es' => 'Islas Åland', 'en' => 'Åland Islands']), 'iso2' => 'AX', 'iso3' => 'AX', 'phone_code' => ''],
            ['id' => 3, 'name' => json_encode(['es' => 'Albania', 'en' => 'Albania']), 'iso2' => 'AL', 'iso3' => 'AL', 'phone_code' => ''],
            ['id' => 4, 'name' => json_encode(['es' => 'Argelia', 'en' => 'Algeria']), 'iso2' => 'DZ', 'iso3' => 'DZ', 'phone_code' => ''],
            ['id' => 5, 'name' => json_encode(['es' => 'Samoa Americana', 'en' => 'American Samoa']), 'iso2' => 'AS', 'iso3' => 'AS', 'phone_code' => ''],
            ['id' => 6, 'name' => json_encode(['es' => 'Andorra', 'en' => 'Andorra']), 'iso2' => 'AD', 'iso3' => 'AD', 'phone_code' => ''],
            ['id' => 7, 'name' => json_encode(['es' => 'Angola', 'en' => 'Angola']), 'iso2' => 'AO', 'iso3' => 'AO', 'phone_code' => ''],
            ['id' => 8, 'name' => json_encode(['es' => 'Anguila', 'en' => 'Anguilla']), 'iso2' => 'AI', 'iso3' => 'AI', 'phone_code' => ''],
            ['id' => 9, 'name' => json_encode(['es' => 'Antártida', 'en' => 'Antarctica']), 'iso2' => 'AQ', 'iso3' => 'AQ', 'phone_code' => ''],
            ['id' => 10, 'name' => json_encode(['es' => 'Antigua y Barbuda', 'en' => 'Antigua and Barbuda']), 'iso2' => 'AG', 'iso3' => 'AG', 'phone_code' => ''],
            ['id' => 11, 'name' => json_encode(['es' => 'Argentina', 'en' => 'Argentina']), 'iso2' => 'AR', 'iso3' => 'AR', 'phone_code' => ''],
            ['id' => 12, 'name' => json_encode(['es' => 'Armenia', 'en' => 'Armenia']), 'iso2' => 'AM', 'iso3' => 'AM', 'phone_code' => ''],
            ['id' => 13, 'name' => json_encode(['es' => 'Aruba', 'en' => 'Aruba']), 'iso2' => 'AW', 'iso3' => 'AW', 'phone_code' => ''],
            ['id' => 14, 'name' => json_encode(['es' => 'Australia', 'en' => 'Australia']), 'iso2' => 'AU', 'iso3' => 'AU', 'phone_code' => ''],
            ['id' => 15, 'name' => json_encode(['es' => 'Austria', 'en' => 'Austria']), 'iso2' => 'AT', 'iso3' => 'AT', 'phone_code' => ''],
            ['id' => 16, 'name' => json_encode(['es' => 'Azerbaiyán', 'en' => 'Azerbaijan']), 'iso2' => 'AZ', 'iso3' => 'AZ', 'phone_code' => ''],
            ['id' => 17, 'name' => json_encode(['es' => 'Bahamas', 'en' => 'Bahamas']), 'iso2' => 'BS', 'iso3' => 'BS', 'phone_code' => ''],
            ['id' => 18, 'name' => json_encode(['es' => 'Baréin', 'en' => 'Bahrain']), 'iso2' => 'BH', 'iso3' => 'BH', 'phone_code' => ''],
            ['id' => 19, 'name' => json_encode(['es' => 'Bangladés', 'en' => 'Bangladesh']), 'iso2' => 'BD', 'iso3' => 'BD', 'phone_code' => ''],
            ['id' => 20, 'name' => json_encode(['es' => 'Barbados', 'en' => 'Barbados']), 'iso2' => 'BB', 'iso3' => 'BB', 'phone_code' => ''],
            ['id' => 21, 'name' => json_encode(['es' => 'Bielorrusia', 'en' => 'Belarus']), 'iso2' => 'BY', 'iso3' => 'BY', 'phone_code' => ''],
            ['id' => 22, 'name' => json_encode(['es' => 'Bélgica', 'en' => 'Belgium']), 'iso2' => 'BE', 'iso3' => 'BE', 'phone_code' => ''],
            ['id' => 23, 'name' => json_encode(['es' => 'Belice', 'en' => 'Belize']), 'iso2' => 'BZ', 'iso3' => 'BZ', 'phone_code' => ''],
            ['id' => 24, 'name' => json_encode(['es' => 'Benín', 'en' => 'Benin']), 'iso2' => 'BJ', 'iso3' => 'BJ', 'phone_code' => ''],
            ['id' => 25, 'name' => json_encode(['es' => 'Bermudas', 'en' => 'Bermuda']), 'iso2' => 'BM', 'iso3' => 'BM', 'phone_code' => ''],
            ['id' => 26, 'name' => json_encode(['es' => 'Bután', 'en' => 'Bhutan']), 'iso2' => 'BT', 'iso3' => 'BT', 'phone_code' => ''],
            ['id' => 27, 'name' => json_encode(['es' => 'Bolivia', 'en' => 'Bolivia']), 'iso2' => 'BO', 'iso3' => 'BO', 'phone_code' => ''],
            ['id' => 28, 'name' => json_encode(['es' => 'Bonaire, San Eustaquio y Saba', 'en' => 'Bonaire, Sint Eustatius and Saba']), 'iso2' => 'BQ', 'iso3' => 'BQ', 'phone_code' => ''],
            ['id' => 29, 'name' => json_encode(['es' => 'Bosnia y Herzegovina', 'en' => 'Bosnia and Herzegovina']), 'iso2' => 'BA', 'iso3' => 'BA', 'phone_code' => ''],
            ['id' => 30, 'name' => json_encode(['es' => 'Botsuana', 'en' => 'Botswana']), 'iso2' => 'BW', 'iso3' => 'BW', 'phone_code' => ''],
            ['id' => 31, 'name' => json_encode(['es' => 'Isla Bouvet', 'en' => 'Bouvet Island']), 'iso2' => 'BV', 'iso3' => 'BV', 'phone_code' => ''],
            ['id' => 32, 'name' => json_encode(['es' => 'Brasil', 'en' => 'Brazil']), 'iso2' => 'BR', 'iso3' => 'BR', 'phone_code' => ''],
            ['id' => 33, 'name' => json_encode(['es' => 'Territorio Británico del Océano Índico', 'en' => 'British Indian Ocean Territory']), 'iso2' => 'IO', 'iso3' => 'IO', 'phone_code' => ''],
            ['id' => 34, 'name' => json_encode(['es' => 'Islas Vírgenes Británicas', 'en' => 'British Virgin Islands']), 'iso2' => 'VG', 'iso3' => 'VG', 'phone_code' => ''],
            ['id' => 35, 'name' => json_encode(['es' => 'Brunéi Darussalam', 'en' => 'Brunei Darussalam']), 'iso2' => 'BN', 'iso3' => 'BN', 'phone_code' => ''],
            ['id' => 36, 'name' => json_encode(['es' => 'Bulgaria', 'en' => 'Bulgaria']), 'iso2' => 'BG', 'iso3' => 'BG', 'phone_code' => ''],
            ['id' => 37, 'name' => json_encode(['es' => 'Burkina Faso', 'en' => 'Burkina Faso']), 'iso2' => 'BF', 'iso3' => 'BF', 'phone_code' => ''],
            ['id' => 38, 'name' => json_encode(['es' => 'Burundi', 'en' => 'Burundi']), 'iso2' => 'BI', 'iso3' => 'BI', 'phone_code' => ''],
            ['id' => 39, 'name' => json_encode(['es' => 'Camboya', 'en' => 'Cambodia']), 'iso2' => 'KH', 'iso3' => 'KH', 'phone_code' => ''],
            ['id' => 40, 'name' => json_encode(['es' => 'Camerún', 'en' => 'Cameroon']), 'iso2' => 'CM', 'iso3' => 'CM', 'phone_code' => ''],
            ['id' => 41, 'name' => json_encode(['es' => 'Canadá', 'en' => 'Canada']), 'iso2' => 'CA', 'iso3' => 'CA', 'phone_code' => ''],
            ['id' => 42, 'name' => json_encode(['es' => 'Cabo Verde', 'en' => 'Cape Verde']), 'iso2' => 'CV', 'iso3' => 'CV', 'phone_code' => ''],
            ['id' => 43, 'name' => json_encode(['es' => 'Islas Caimán', 'en' => 'Cayman Islands']), 'iso2' => 'KY', 'iso3' => 'KY', 'phone_code' => ''],
            ['id' => 44, 'name' => json_encode(['es' => 'República Centroafricana', 'en' => 'Central African Republic']), 'iso2' => 'CF', 'iso3' => 'CF', 'phone_code' => ''],
            ['id' => 45, 'name' => json_encode(['es' => 'Chad', 'en' => 'Chad']), 'iso2' => 'TD', 'iso3' => 'TD', 'phone_code' => ''],
            ['id' => 46, 'name' => json_encode(['es' => 'Chile', 'en' => 'Chile']), 'iso2' => 'CL', 'iso3' => 'CL', 'phone_code' => ''],
            ['id' => 47, 'name' => json_encode(['es' => 'China', 'en' => 'China']), 'iso2' => 'CN', 'iso3' => 'CN', 'phone_code' => ''],
            ['id' => 48, 'name' => json_encode(['es' => 'Isla de Navidad', 'en' => 'Christmas Island']), 'iso2' => 'CX', 'iso3' => 'CX', 'phone_code' => ''],
            ['id' => 49, 'name' => json_encode(['es' => 'Islas Cocos (Keeling)', 'en' => 'Cocos (Keeling) Islands']), 'iso2' => 'CC', 'iso3' => 'CC', 'phone_code' => ''],
            ['id' => 50, 'name' => json_encode(['es' => 'Colombia', 'en' => 'Colombia']), 'iso2' => 'CO', 'iso3' => 'CO', 'phone_code' => ''],
            ['id' => 51, 'name' => json_encode(['es' => 'Comoras', 'en' => 'Comoros']), 'iso2' => 'KM', 'iso3' => 'KM', 'phone_code' => ''],
            ['id' => 52, 'name' => json_encode(['es' => 'Congo (Brazzaville)', 'en' => 'Congo (Brazzaville)']), 'iso2' => 'CG', 'iso3' => 'CG', 'phone_code' => ''],
            ['id' => 53, 'name' => json_encode(['es' => 'Congo DR', 'en' => 'Congo DR']), 'iso2' => 'CD', 'iso3' => 'CD', 'phone_code' => ''],
            ['id' => 54, 'name' => json_encode(['es' => 'Islas Cook', 'en' => 'Cook Islands']), 'iso2' => 'CK', 'iso3' => 'CK', 'phone_code' => ''],
            ['id' => 55, 'name' => json_encode(['es' => 'Costa Rica', 'en' => 'Costa Rica']), 'iso2' => 'CR', 'iso3' => 'CR', 'phone_code' => ''],
            ['id' => 56, 'name' => json_encode(['es' => 'Costa de Marfil', 'en' => 'Côte D\'Ivoire']), 'iso2' => 'CI', 'iso3' => 'CI', 'phone_code' => ''],
            ['id' => 57, 'name' => json_encode(['es' => 'Croacia', 'en' => 'Croatia']), 'iso2' => 'HR', 'iso3' => 'HR', 'phone_code' => ''],
            ['id' => 58, 'name' => json_encode(['es' => 'Cuba', 'en' => 'Cuba']), 'iso2' => 'CU', 'iso3' => 'CU', 'phone_code' => ''],
            ['id' => 59, 'name' => json_encode(['es' => 'Curazao', 'en' => 'Curaçao']), 'iso2' => 'CW', 'iso3' => 'CW', 'phone_code' => ''],
            ['id' => 60, 'name' => json_encode(['es' => 'Chipre', 'en' => 'Cyprus']), 'iso2' => 'CY', 'iso3' => 'CY', 'phone_code' => ''],
            ['id' => 61, 'name' => json_encode(['es' => 'República Checa', 'en' => 'Czech Republic']), 'iso2' => 'CZ', 'iso3' => 'CZ', 'phone_code' => ''],
            ['id' => 62, 'name' => json_encode(['es' => 'Dinamarca', 'en' => 'Denmark']), 'iso2' => 'DK', 'iso3' => 'DK', 'phone_code' => ''],
            ['id' => 63, 'name' => json_encode(['es' => 'Yibuti', 'en' => 'Djibouti']), 'iso2' => 'DJ', 'iso3' => 'DJ', 'phone_code' => ''],
            ['id' => 64, 'name' => json_encode(['es' => 'Dominica', 'en' => 'Dominica']), 'iso2' => 'DM', 'iso3' => 'DM', 'phone_code' => ''],
            ['id' => 65, 'name' => json_encode(['es' => 'República Dominicana', 'en' => 'Dominican Republic']), 'iso2' => 'DO', 'iso3' => 'DO', 'phone_code' => ''],
            ['id' => 66, 'name' => json_encode(['es' => 'Timor Oriental', 'en' => 'East Timor']), 'iso2' => 'TL', 'iso3' => 'TL', 'phone_code' => ''],
            ['id' => 67, 'name' => json_encode(['es' => 'Ecuador', 'en' => 'Ecuador']), 'iso2' => 'EC', 'iso3' => 'EC', 'phone_code' => ''],
            ['id' => 68, 'name' => json_encode(['es' => 'Egipto', 'en' => 'Egypt']), 'iso2' => 'EG', 'iso3' => 'EG', 'phone_code' => ''],
            ['id' => 69, 'name' => json_encode(['es' => 'El Salvador', 'en' => 'El Salvador']), 'iso2' => 'SV', 'iso3' => 'SV', 'phone_code' => ''],
            ['id' => 70, 'name' => json_encode(['es' => 'Guinea Ecuatorial', 'en' => 'Equatorial Guinea']), 'iso2' => 'GQ', 'iso3' => 'GQ', 'phone_code' => ''],
            ['id' => 71, 'name' => json_encode(['es' => 'Eritrea', 'en' => 'Eritrea']), 'iso2' => 'ER', 'iso3' => 'ER', 'phone_code' => ''],
            ['id' => 72, 'name' => json_encode(['es' => 'Estonia', 'en' => 'Estonia']), 'iso2' => 'EE', 'iso3' => 'EE', 'phone_code' => ''],
            ['id' => 73, 'name' => json_encode(['es' => 'Etiopia', 'en' => 'Ethiopia']), 'iso2' => 'ET', 'iso3' => 'ET', 'phone_code' => ''],
            ['id' => 74, 'name' => json_encode(['es' => 'Falkland Islands', 'en' => 'Falkland Islands']), 'iso2' => 'FK', 'iso3' => 'FK', 'phone_code' => ''],
            ['id' => 75, 'name' => json_encode(['es' => 'Faroe Islands', 'en' => 'Faroe Islands']), 'iso2' => 'FO', 'iso3' => 'FO', 'phone_code' => ''],
            ['id' => 76, 'name' => json_encode(['es' => 'Fiji', 'en' => 'Fiji']), 'iso2' => 'FJ', 'iso3' => 'FJ', 'phone_code' => ''],
            ['id' => 77, 'name' => json_encode(['es' => 'Finlandia', 'en' => 'Finland']), 'iso2' => 'FI', 'iso3' => 'FI', 'phone_code' => ''],
            ['id' => 78, 'name' => json_encode(['es' => 'Francia', 'en' => 'France']), 'iso2' => 'FR', 'iso3' => 'FR', 'phone_code' => ''],
            ['id' => 79, 'name' => json_encode(['es' => 'Guayana Francesa', 'en' => 'French Guiana']), 'iso2' => 'GF', 'iso3' => 'GF', 'phone_code' => ''],
            ['id' => 80, 'name' => json_encode(['es' => 'French Polynesia', 'en' => 'French Polynesia']), 'iso2' => 'PF', 'iso3' => 'PF', 'phone_code' => ''],
            ['id' => 81, 'name' => json_encode(['es' => 'French Southern Territories', 'en' => 'French Southern Territories']), 'iso2' => 'TF', 'iso3' => 'TF', 'phone_code' => ''],
            ['id' => 82, 'name' => json_encode(['es' => 'Gabon', 'en' => 'Gabon']), 'iso2' => 'GA', 'iso3' => 'GA', 'phone_code' => ''],
            ['id' => 83, 'name' => json_encode(['es' => 'Gambia', 'en' => 'Gambia']), 'iso2' => 'GM', 'iso3' => 'GM', 'phone_code' => ''],
            ['id' => 84, 'name' => json_encode(['es' => 'Georgia', 'en' => 'Georgia']), 'iso2' => 'GE', 'iso3' => 'GE', 'phone_code' => ''],
            ['id' => 85, 'name' => json_encode(['es' => 'Alemania', 'en' => 'Germany']), 'iso2' => 'DE', 'iso3' => 'DE', 'phone_code' => ''],
            ['id' => 86, 'name' => json_encode(['es' => 'Ghana', 'en' => 'Ghana']), 'iso2' => 'GH', 'iso3' => 'GH', 'phone_code' => ''],
            ['id' => 87, 'name' => json_encode(['es' => 'Gibraltar', 'en' => 'Gibraltar']), 'iso2' => 'GI', 'iso3' => 'GI', 'phone_code' => ''],
            ['id' => 88, 'name' => json_encode(['es' => 'Grecia', 'en' => 'Greece']), 'iso2' => 'GR', 'iso3' => 'GR', 'phone_code' => ''],
            ['id' => 89, 'name' => json_encode(['es' => 'Greenland', 'en' => 'Greenland']), 'iso2' => 'GL', 'iso3' => 'GL', 'phone_code' => ''],
            ['id' => 90, 'name' => json_encode(['es' => 'Grenada', 'en' => 'Grenada']), 'iso2' => 'GD', 'iso3' => 'GD', 'phone_code' => ''],
            ['id' => 91, 'name' => json_encode(['es' => 'Guadeloupe', 'en' => 'Guadeloupe']), 'iso2' => 'GP', 'iso3' => 'GP', 'phone_code' => ''],
            ['id' => 92, 'name' => json_encode(['es' => 'Guam', 'en' => 'Guam']), 'iso2' => 'GU', 'iso3' => 'GU', 'phone_code' => ''],
            ['id' => 93, 'name' => json_encode(['es' => 'Guatemala', 'en' => 'Guatemala']), 'iso2' => 'GT', 'iso3' => 'GT', 'phone_code' => ''],
            ['id' => 94, 'name' => json_encode(['es' => 'Guernsey', 'en' => 'Guernsey']), 'iso2' => 'GG', 'iso3' => 'GG', 'phone_code' => ''],
            ['id' => 95, 'name' => json_encode(['es' => 'Guinea', 'en' => 'Guinea']), 'iso2' => 'GN', 'iso3' => 'GN', 'phone_code' => ''],
            ['id' => 96, 'name' => json_encode(['es' => 'Guinea-Bissau', 'en' => 'Guinea-Bissau']), 'iso2' => 'GW', 'iso3' => 'GW', 'phone_code' => ''],
            ['id' => 97, 'name' => json_encode(['es' => 'Guyana', 'en' => 'Guyana']), 'iso2' => 'GY', 'iso3' => 'GY', 'phone_code' => ''],
            ['id' => 98, 'name' => json_encode(['es' => 'Haiti', 'en' => 'Haiti']), 'iso2' => 'HT', 'iso3' => 'HT', 'phone_code' => ''],
            ['id' => 99, 'name' => json_encode(['es' => 'Heard Island and McDonald Islands', 'en' => 'Heard Island and McDonald Islands']), 'iso2' => 'HM', 'iso3' => 'HM', 'phone_code' => ''],
            ['id' => 100, 'name' => json_encode(['es' => 'Honduras', 'en' => 'Honduras']), 'iso2' => 'HN', 'iso3' => 'HN', 'phone_code' => ''],
            ['id' => 101, 'name' => json_encode(['es' => 'Hong Kong', 'en' => 'Hong Kong']), 'iso2' => 'HK', 'iso3' => 'HK', 'phone_code' => ''],
            ['id' => 102, 'name' => json_encode(['es' => 'Hungary', 'en' => 'Hungary']), 'iso2' => 'HU', 'iso3' => 'HU', 'phone_code' => ''],
            ['id' => 103, 'name' => json_encode(['es' => 'Iceland', 'en' => 'Iceland']), 'iso2' => 'IS', 'iso3' => 'IS', 'phone_code' => ''],
            ['id' => 104, 'name' => json_encode(['es' => 'India', 'en' => 'India']), 'iso2' => 'IN', 'iso3' => 'IN', 'phone_code' => ''],
            ['id' => 105, 'name' => json_encode(['es' => 'Indonesia', 'en' => 'Indonesia']), 'iso2' => 'ID', 'iso3' => 'ID', 'phone_code' => ''],
            ['id' => 106, 'name' => json_encode(['es' => 'Iran', 'en' => 'Iran']), 'iso2' => 'IR', 'iso3' => 'IR', 'phone_code' => ''],
            ['id' => 107, 'name' => json_encode(['es' => 'Iraq', 'en' => 'Iraq']), 'iso2' => 'IQ', 'iso3' => 'IQ', 'phone_code' => ''],
            ['id' => 108, 'name' => json_encode(['es' => 'Ireland', 'en' => 'Ireland']), 'iso2' => 'IE', 'iso3' => 'IE', 'phone_code' => ''],
            ['id' => 109, 'name' => json_encode(['es' => 'Isle of Man', 'en' => 'Isle of Man']), 'iso2' => 'IM', 'iso3' => 'IM', 'phone_code' => ''],
            ['id' => 110, 'name' => json_encode(['es' => 'Israel', 'en' => 'Israel']), 'iso2' => 'IL', 'iso3' => 'IL', 'phone_code' => ''],
            ['id' => 111, 'name' => json_encode(['es' => 'Italia', 'en' => 'Italy']), 'iso2' => 'IT', 'iso3' => 'IT', 'phone_code' => ''],
            ['id' => 112, 'name' => json_encode(['es' => 'Jamaica', 'en' => 'Jamaica']), 'iso2' => 'JM', 'iso3' => 'JM', 'phone_code' => ''],
            ['id' => 113, 'name' => json_encode(['es' => 'Japón', 'en' => 'Japan']), 'iso2' => 'JP', 'iso3' => 'JP', 'phone_code' => ''],
            ['id' => 114, 'name' => json_encode(['es' => 'Jersey', 'en' => 'Jersey']), 'iso2' => 'JE', 'iso3' => 'JE', 'phone_code' => ''],
            ['id' => 115, 'name' => json_encode(['es' => 'Jordan', 'en' => 'Jordan']), 'iso2' => 'JO', 'iso3' => 'JO', 'phone_code' => ''],
            ['id' => 116, 'name' => json_encode(['es' => 'Kazakhstan', 'en' => 'Kazakhstan']), 'iso2' => 'KZ', 'iso3' => 'KZ', 'phone_code' => ''],
            ['id' => 117, 'name' => json_encode(['es' => 'Kenia', 'en' => 'Kenya']), 'iso2' => 'KE', 'iso3' => 'KE', 'phone_code' => ''],
            ['id' => 118, 'name' => json_encode(['es' => 'Kiribati', 'en' => 'Kiribati']), 'iso2' => 'KI', 'iso3' => 'KI', 'phone_code' => ''],
            ['id' => 119, 'name' => json_encode(['es' => 'Kosovo', 'en' => 'Kosovo']), 'iso2' => 'XK', 'iso3' => 'XK', 'phone_code' => ''],
            ['id' => 120, 'name' => json_encode(['es' => 'Kuwait', 'en' => 'Kuwait']), 'iso2' => 'KW', 'iso3' => 'KW', 'phone_code' => ''],
            ['id' => 121, 'name' => json_encode(['es' => 'Kyrgyzstan', 'en' => 'Kyrgyzstan']), 'iso2' => 'KG', 'iso3' => 'KG', 'phone_code' => ''],
            ['id' => 122, 'name' => json_encode(['es' => 'Laos', 'en' => 'Laos']), 'iso2' => 'LA', 'iso3' => 'LA', 'phone_code' => ''],
            ['id' => 123, 'name' => json_encode(['es' => 'Latvia', 'en' => 'Latvia']), 'iso2' => 'LV', 'iso3' => 'LV', 'phone_code' => ''],
            ['id' => 124, 'name' => json_encode(['es' => 'Lebanon', 'en' => 'Lebanon']), 'iso2' => 'LB', 'iso3' => 'LB', 'phone_code' => ''],
            ['id' => 125, 'name' => json_encode(['es' => 'Lesotho', 'en' => 'Lesotho']), 'iso2' => 'LS', 'iso3' => 'LS', 'phone_code' => ''],
            ['id' => 126, 'name' => json_encode(['es' => 'Liberia', 'en' => 'Liberia']), 'iso2' => 'LR', 'iso3' => 'LR', 'phone_code' => ''],
            ['id' => 127, 'name' => json_encode(['es' => 'Libya', 'en' => 'Libya']), 'iso2' => 'LY', 'iso3' => 'LY', 'phone_code' => ''],
            ['id' => 128, 'name' => json_encode(['es' => 'Liechtenstein', 'en' => 'Liechtenstein']), 'iso2' => 'LI', 'iso3' => 'LI', 'phone_code' => ''],
            ['id' => 129, 'name' => json_encode(['es' => 'Lithuania', 'en' => 'Lithuania']), 'iso2' => 'LT', 'iso3' => 'LT', 'phone_code' => ''],
            ['id' => 130, 'name' => json_encode(['es' => 'Luxembourg', 'en' => 'Luxembourg']), 'iso2' => 'LU', 'iso3' => 'LU', 'phone_code' => ''],
            ['id' => 131, 'name' => json_encode(['es' => 'Macau', 'en' => 'Macau']), 'iso2' => 'MO', 'iso3' => 'MO', 'phone_code' => ''],
            ['id' => 132, 'name' => json_encode(['es' => 'Macedonia', 'en' => 'Macedonia']), 'iso2' => 'MK', 'iso3' => 'MK', 'phone_code' => ''],
            ['id' => 133, 'name' => json_encode(['es' => 'Madagascar', 'en' => 'Madagascar']), 'iso2' => 'MG', 'iso3' => 'MG', 'phone_code' => ''],
            ['id' => 134, 'name' => json_encode(['es' => 'Malawi', 'en' => 'Malawi']), 'iso2' => 'MW', 'iso3' => 'MW', 'phone_code' => ''],
            ['id' => 135, 'name' => json_encode(['es' => 'Malaysia', 'en' => 'Malaysia']), 'iso2' => 'MY', 'iso3' => 'MY', 'phone_code' => ''],
            ['id' => 136, 'name' => json_encode(['es' => 'Maldives', 'en' => 'Maldives']), 'iso2' => 'MV', 'iso3' => 'MV', 'phone_code' => ''],
            ['id' => 137, 'name' => json_encode(['es' => 'Mali', 'en' => 'Mali']), 'iso2' => 'ML', 'iso3' => 'ML', 'phone_code' => ''],
            ['id' => 138, 'name' => json_encode(['es' => 'Malta', 'en' => 'Malta']), 'iso2' => 'MT', 'iso3' => 'MT', 'phone_code' => ''],
            ['id' => 139, 'name' => json_encode(['es' => 'Islas Marshall', 'en' => 'Marshall Islands']), 'iso2' => 'MH', 'iso3' => 'MH', 'phone_code' => ''],
            ['id' => 140, 'name' => json_encode(['es' => 'Martinique', 'en' => 'Martinique']), 'iso2' => 'MQ', 'iso3' => 'MQ', 'phone_code' => ''],
            ['id' => 141, 'name' => json_encode(['es' => 'Mauritania', 'en' => 'Mauritania']), 'iso2' => 'MR', 'iso3' => 'MR', 'phone_code' => ''],
            ['id' => 142, 'name' => json_encode(['es' => 'Mauritius', 'en' => 'Mauritius']), 'iso2' => 'MU', 'iso3' => 'MU', 'phone_code' => ''],
            ['id' => 143, 'name' => json_encode(['es' => 'Mayotte', 'en' => 'Mayotte']), 'iso2' => 'YT', 'iso3' => 'YT', 'phone_code' => ''],
            ['id' => 144, 'name' => json_encode(['es' => 'Mexico', 'en' => 'Mexico']), 'iso2' => 'MX', 'iso3' => 'MX', 'phone_code' => ''],
            ['id' => 145, 'name' => json_encode(['es' => 'Micronesia', 'en' => 'Micronesia']), 'iso2' => 'FM', 'iso3' => 'FM', 'phone_code' => ''],
            ['id' => 146, 'name' => json_encode(['es' => 'Moldova', 'en' => 'Moldova']), 'iso2' => 'MD', 'iso3' => 'MD', 'phone_code' => ''],
            ['id' => 147, 'name' => json_encode(['es' => 'Monaco', 'en' => 'Monaco']), 'iso2' => 'MC', 'iso3' => 'MC', 'phone_code' => ''],
            ['id' => 148, 'name' => json_encode(['es' => 'Mongolia', 'en' => 'Mongolia']), 'iso2' => 'MN', 'iso3' => 'MN', 'phone_code' => ''],
            ['id' => 149, 'name' => json_encode(['es' => 'Montenegro', 'en' => 'Montenegro']), 'iso2' => 'ME', 'iso3' => 'ME', 'phone_code' => ''],
            ['id' => 150, 'name' => json_encode(['es' => 'Montserrat', 'en' => 'Montserrat']), 'iso2' => 'MS', 'iso3' => 'MS', 'phone_code' => ''],
            ['id' => 151, 'name' => json_encode(['es' => 'Marruecos', 'en' => 'Morocco']), 'iso2' => 'MA', 'iso3' => 'MA', 'phone_code' => ''],
            ['id' => 152, 'name' => json_encode(['es' => 'Mozambique', 'en' => 'Mozambique']), 'iso2' => 'MZ', 'iso3' => 'MZ', 'phone_code' => ''],
            ['id' => 153, 'name' => json_encode(['es' => 'Myanmar', 'en' => 'Myanmar']), 'iso2' => 'MM', 'iso3' => 'MM', 'phone_code' => ''],
            ['id' => 154, 'name' => json_encode(['es' => 'Namibia', 'en' => 'Namibia']), 'iso2' => 'NA', 'iso3' => 'NA', 'phone_code' => ''],
            ['id' => 155, 'name' => json_encode(['es' => 'Nauru', 'en' => 'Nauru']), 'iso2' => 'NR', 'iso3' => 'NR', 'phone_code' => ''],
            ['id' => 156, 'name' => json_encode(['es' => 'Nepal', 'en' => 'Nepal']), 'iso2' => 'NP', 'iso3' => 'NP', 'phone_code' => ''],
            ['id' => 157, 'name' => json_encode(['es' => 'Paises Bajos', 'en' => 'Netherlands']), 'iso2' => 'NL', 'iso3' => 'NL', 'phone_code' => ''],
            ['id' => 158, 'name' => json_encode(['es' => 'Netherlands Antilles', 'en' => 'Netherlands Antilles']), 'iso2' => 'AN', 'iso3' => 'AN', 'phone_code' => ''],
            ['id' => 159, 'name' => json_encode(['es' => 'New Caledonia', 'en' => 'New Caledonia']), 'iso2' => 'NC', 'iso3' => 'NC', 'phone_code' => ''],
            ['id' => 160, 'name' => json_encode(['es' => 'New Zealand', 'en' => 'New Zealand']), 'iso2' => 'NZ', 'iso3' => 'NZ', 'phone_code' => ''],
            ['id' => 161, 'name' => json_encode(['es' => 'Nicaragua', 'en' => 'Nicaragua']), 'iso2' => 'NI', 'iso3' => 'NI', 'phone_code' => ''],
            ['id' => 162, 'name' => json_encode(['es' => 'Niger', 'en' => 'Niger']), 'iso2' => 'NE', 'iso3' => 'NE', 'phone_code' => ''],
            ['id' => 163, 'name' => json_encode(['es' => 'Nigeria', 'en' => 'Nigeria']), 'iso2' => 'NG', 'iso3' => 'NG', 'phone_code' => ''],
            ['id' => 164, 'name' => json_encode(['es' => 'Niue', 'en' => 'Niue']), 'iso2' => 'NU', 'iso3' => 'NU', 'phone_code' => ''],
            ['id' => 165, 'name' => json_encode(['es' => 'Norfolk Island', 'en' => 'Norfolk Island']), 'iso2' => 'NF', 'iso3' => 'NF', 'phone_code' => ''],
            ['id' => 166, 'name' => json_encode(['es' => 'North Korea', 'en' => 'North Korea']), 'iso2' => 'KP', 'iso3' => 'KP', 'phone_code' => ''],
            ['id' => 167, 'name' => json_encode(['es' => 'Northern Mariana Islands', 'en' => 'Northern Mariana Islands']), 'iso2' => 'MP', 'iso3' => 'MP', 'phone_code' => ''],
            ['id' => 168, 'name' => json_encode(['es' => 'Norway', 'en' => 'Norway']), 'iso2' => 'NO', 'iso3' => 'NO', 'phone_code' => ''],
            ['id' => 169, 'name' => json_encode(['es' => 'Oman', 'en' => 'Oman']), 'iso2' => 'OM', 'iso3' => 'OM', 'phone_code' => ''],
            ['id' => 170, 'name' => json_encode(['es' => 'Pakistan', 'en' => 'Pakistan']), 'iso2' => 'PK', 'iso3' => 'PK', 'phone_code' => ''],
            ['id' => 171, 'name' => json_encode(['es' => 'Palau', 'en' => 'Palau']), 'iso2' => 'PW', 'iso3' => 'PW', 'phone_code' => ''],
            ['id' => 172, 'name' => json_encode(['es' => 'Palestinian Territory (Gaza Strip)', 'en' => 'Palestinian Territory (Gaza Strip)']), 'iso2' => 'PS', 'iso3' => 'PS', 'phone_code' => ''],
            ['id' => 173, 'name' => json_encode(['es' => 'Panama', 'en' => 'Panama']), 'iso2' => 'PA', 'iso3' => 'PA', 'phone_code' => ''],
            ['id' => 174, 'name' => json_encode(['es' => 'Papua New Guinea', 'en' => 'Papua New Guinea']), 'iso2' => 'PG', 'iso3' => 'PG', 'phone_code' => ''],
            ['id' => 175, 'name' => json_encode(['es' => 'Paraguay', 'en' => 'Paraguay']), 'iso2' => 'PY', 'iso3' => 'PY', 'phone_code' => ''],
            ['id' => 176, 'name' => json_encode(['es' => 'Peru', 'en' => 'Peru']), 'iso2' => 'PE', 'iso3' => 'PE', 'phone_code' => ''],
            ['id' => 177, 'name' => json_encode(['es' => 'Philippines', 'en' => 'Philippines']), 'iso2' => 'PH', 'iso3' => 'PH', 'phone_code' => ''],
            ['id' => 178, 'name' => json_encode(['es' => 'Pitcairn Islands', 'en' => 'Pitcairn Islands']), 'iso2' => 'PN', 'iso3' => 'PN', 'phone_code' => ''],
            ['id' => 179, 'name' => json_encode(['es' => 'Polonia', 'en' => 'Poland']), 'iso2' => 'PL', 'iso3' => 'PL', 'phone_code' => ''],
            ['id' => 180, 'name' => json_encode(['es' => 'Portugal', 'en' => 'Portugal']), 'iso2' => 'PT', 'iso3' => 'PT', 'phone_code' => '351'],
            ['id' => 181, 'name' => json_encode(['es' => 'Puerto Rico', 'en' => 'Puerto Rico']), 'iso2' => 'PR', 'iso3' => 'PR', 'phone_code' => ''],
            ['id' => 182, 'name' => json_encode(['es' => 'Qatar', 'en' => 'Qatar']), 'iso2' => 'QA', 'iso3' => 'QA', 'phone_code' => ''],
            ['id' => 183, 'name' => json_encode(['es' => 'Réunion', 'en' => 'Réunion']), 'iso2' => 'RE', 'iso3' => 'RE', 'phone_code' => ''],
            ['id' => 184, 'name' => json_encode(['es' => 'Romania', 'en' => 'Romania']), 'iso2' => 'RO', 'iso3' => 'RO', 'phone_code' => ''],
            ['id' => 185, 'name' => json_encode(['es' => 'Russia', 'en' => 'Russia']), 'iso2' => 'RU', 'iso3' => 'RU', 'phone_code' => ''],
            ['id' => 186, 'name' => json_encode(['es' => 'Rwanda', 'en' => 'Rwanda']), 'iso2' => 'RW', 'iso3' => 'RW', 'phone_code' => ''],
            ['id' => 187, 'name' => json_encode(['es' => 'Saint Barthélemy', 'en' => 'Saint Barthélemy']), 'iso2' => 'BL', 'iso3' => 'BL', 'phone_code' => ''],
            ['id' => 188, 'name' => json_encode(['es' => 'Saint Helena, Ascension and Tristan Da Cunha', 'en' => 'Saint Helena, Ascension and Tristan Da Cunha']), 'iso2' => 'SH', 'iso3' => 'SH', 'phone_code' => ''],
            ['id' => 189, 'name' => json_encode(['es' => 'Saint Kitts and Nevis', 'en' => 'Saint Kitts and Nevis']), 'iso2' => 'KN', 'iso3' => 'KN', 'phone_code' => ''],
            ['id' => 190, 'name' => json_encode(['es' => 'Saint Lucia', 'en' => 'Saint Lucia']), 'iso2' => 'LC', 'iso3' => 'LC', 'phone_code' => ''],
            ['id' => 191, 'name' => json_encode(['es' => 'Saint Martin', 'en' => 'Saint Martin']), 'iso2' => 'MF', 'iso3' => 'MF', 'phone_code' => ''],
            ['id' => 192, 'name' => json_encode(['es' => 'Saint Martin', 'en' => 'Saint Martin']), 'iso2' => 'SX', 'iso3' => 'SX', 'phone_code' => ''],
            ['id' => 193, 'name' => json_encode(['es' => 'Saint Pierre and Miquelon', 'en' => 'Saint Pierre and Miquelon']), 'iso2' => 'PM', 'iso3' => 'PM', 'phone_code' => ''],
            ['id' => 194, 'name' => json_encode(['es' => 'Saint Vincent and the Grenadines', 'en' => 'Saint Vincent and the Grenadines']), 'iso2' => 'VC', 'iso3' => 'VC', 'phone_code' => ''],
            ['id' => 195, 'name' => json_encode(['es' => 'Samoa', 'en' => 'Samoa']), 'iso2' => 'WS', 'iso3' => 'WS', 'phone_code' => ''],
            ['id' => 196, 'name' => json_encode(['es' => 'San Marino', 'en' => 'San Marino']), 'iso2' => 'SM', 'iso3' => 'SM', 'phone_code' => ''],
            ['id' => 197, 'name' => json_encode(['es' => 'São Tomé and Príncipe', 'en' => 'São Tomé and Príncipe']), 'iso2' => 'ST', 'iso3' => 'ST', 'phone_code' => ''],
            ['id' => 198, 'name' => json_encode(['es' => 'Saudi Arabia', 'en' => 'Saudi Arabia']), 'iso2' => 'SA', 'iso3' => 'SA', 'phone_code' => ''],
            ['id' => 199, 'name' => json_encode(['es' => 'Senegal', 'en' => 'Senegal']), 'iso2' => 'SN', 'iso3' => 'SN', 'phone_code' => ''],
            ['id' => 200, 'name' => json_encode(['es' => 'Serbia', 'en' => 'Serbia']), 'iso2' => 'RS', 'iso3' => 'RS', 'phone_code' => ''],
            ['id' => 201, 'name' => json_encode(['es' => 'Seychelles', 'en' => 'Seychelles']), 'iso2' => 'SC', 'iso3' => 'SC', 'phone_code' => ''],
            ['id' => 202, 'name' => json_encode(['es' => 'Sierra Leone', 'en' => 'Sierra Leone']), 'iso2' => 'SL', 'iso3' => 'SL', 'phone_code' => ''],
            ['id' => 203, 'name' => json_encode(['es' => 'Singapore', 'en' => 'Singapore']), 'iso2' => 'SG', 'iso3' => 'SG', 'phone_code' => ''],
            ['id' => 204, 'name' => json_encode(['es' => 'Slovakia', 'en' => 'Slovakia']), 'iso2' => 'SK', 'iso3' => 'SK', 'phone_code' => ''],
            ['id' => 205, 'name' => json_encode(['es' => 'Slovenia', 'en' => 'Slovenia']), 'iso2' => 'SI', 'iso3' => 'SI', 'phone_code' => ''],
            ['id' => 206, 'name' => json_encode(['es' => 'Solomon Islands', 'en' => 'Solomon Islands']), 'iso2' => 'SB', 'iso3' => 'SB', 'phone_code' => ''],
            ['id' => 207, 'name' => json_encode(['es' => 'Somalia', 'en' => 'Somalia']), 'iso2' => 'SO', 'iso3' => 'SO', 'phone_code' => ''],
            ['id' => 208, 'name' => json_encode(['es' => 'South Africa', 'en' => 'South Africa']), 'iso2' => 'ZA', 'iso3' => 'ZA', 'phone_code' => ''],
            ['id' => 209, 'name' => json_encode(['es' => 'South Georgia and the South Sandwich Islands', 'en' => 'South Georgia and the South Sandwich Islands']), 'iso2' => 'GS', 'iso3' => 'GS', 'phone_code' => ''],
            ['id' => 210, 'name' => json_encode(['es' => 'South Korea', 'en' => 'South Korea']), 'iso2' => 'KR', 'iso3' => 'KR', 'phone_code' => ''],
            ['id' => 211, 'name' => json_encode(['es' => 'South Sudan', 'en' => 'South Sudan']), 'iso2' => 'SS', 'iso3' => 'SS', 'phone_code' => ''],
            ['id' => 212, 'name' => json_encode(['es' => 'España', 'en' => 'Spain']), 'iso2' => 'ES', 'iso3' => 'ES', 'phone_code' => '34'],
            ['id' => 213, 'name' => json_encode(['es' => 'Sri Lanka', 'en' => 'Sri Lanka']), 'iso2' => 'LK', 'iso3' => 'LK', 'phone_code' => ''],
            ['id' => 214, 'name' => json_encode(['es' => 'Sudan', 'en' => 'Sudan']), 'iso2' => 'SD', 'iso3' => 'SD', 'phone_code' => ''],
            ['id' => 215, 'name' => json_encode(['es' => 'Suriname', 'en' => 'Suriname']), 'iso2' => 'SR', 'iso3' => 'SR', 'phone_code' => ''],
            ['id' => 216, 'name' => json_encode(['es' => 'Svalbard and Jan Mayen', 'en' => 'Svalbard and Jan Mayen']), 'iso2' => 'SJ', 'iso3' => 'SJ', 'phone_code' => ''],
            ['id' => 217, 'name' => json_encode(['es' => 'Swaziland', 'en' => 'Swaziland']), 'iso2' => 'SZ', 'iso3' => 'SZ', 'phone_code' => ''],
            ['id' => 218, 'name' => json_encode(['es' => 'Suecia', 'en' => 'Sweden']), 'iso2' => 'SE', 'iso3' => 'SE', 'phone_code' => ''],
            ['id' => 219, 'name' => json_encode(['es' => 'Suiza', 'en' => 'Switzerland']), 'iso2' => 'CH', 'iso3' => 'CH', 'phone_code' => ''],
            ['id' => 220, 'name' => json_encode(['es' => 'Syria', 'en' => 'Syria']), 'iso2' => 'SY', 'iso3' => 'SY', 'phone_code' => ''],
            ['id' => 221, 'name' => json_encode(['es' => 'Taiwan', 'en' => 'Taiwan']), 'iso2' => 'TW', 'iso3' => 'TW', 'phone_code' => ''],
            ['id' => 222, 'name' => json_encode(['es' => 'Tajikistan', 'en' => 'Tajikistan']), 'iso2' => 'TJ', 'iso3' => 'TJ', 'phone_code' => ''],
            ['id' => 223, 'name' => json_encode(['es' => 'Tanzania', 'en' => 'Tanzania']), 'iso2' => 'TZ', 'iso3' => 'TZ', 'phone_code' => ''],
            ['id' => 224, 'name' => json_encode(['es' => 'Thailand', 'en' => 'Thailand']), 'iso2' => 'TH', 'iso3' => 'TH', 'phone_code' => ''],
            ['id' => 225, 'name' => json_encode(['es' => 'Togo', 'en' => 'Togo']), 'iso2' => 'TG', 'iso3' => 'TG', 'phone_code' => ''],
            ['id' => 226, 'name' => json_encode(['es' => 'Tokelau', 'en' => 'Tokelau']), 'iso2' => 'TK', 'iso3' => 'TK', 'phone_code' => ''],
            ['id' => 227, 'name' => json_encode(['es' => 'Tonga', 'en' => 'Tonga']), 'iso2' => 'TO', 'iso3' => 'TO', 'phone_code' => ''],
            ['id' => 228, 'name' => json_encode(['es' => 'Trinidad and Tobago', 'en' => 'Trinidad and Tobago']), 'iso2' => 'TT', 'iso3' => 'TT', 'phone_code' => ''],
            ['id' => 229, 'name' => json_encode(['es' => 'Túnez', 'en' => 'Tunisia']), 'iso2' => 'TN', 'iso3' => 'TN', 'phone_code' => ''],
            ['id' => 230, 'name' => json_encode(['es' => 'Turquia', 'en' => 'Turkey']), 'iso2' => 'TR', 'iso3' => 'TR', 'phone_code' => ''],
            ['id' => 231, 'name' => json_encode(['es' => 'Turkmenistan', 'en' => 'Turkmenistan']), 'iso2' => 'TM', 'iso3' => 'TM', 'phone_code' => ''],
            ['id' => 232, 'name' => json_encode(['es' => 'Turks and Caicos', 'en' => 'Turks and Caicos']), 'iso2' => 'TC', 'iso3' => 'TC', 'phone_code' => ''],
            ['id' => 233, 'name' => json_encode(['es' => 'Tuvalu', 'en' => 'Tuvalu']), 'iso2' => 'TV', 'iso3' => 'TV', 'phone_code' => ''],
            ['id' => 234, 'name' => json_encode(['es' => 'Uganda', 'en' => 'Uganda']), 'iso2' => 'UG', 'iso3' => 'UG', 'phone_code' => ''],
            ['id' => 235, 'name' => json_encode(['es' => 'Ukraine', 'en' => 'Ukraine']), 'iso2' => 'UA', 'iso3' => 'UA', 'phone_code' => ''],
            ['id' => 236, 'name' => json_encode(['es' => 'United Arab Emirates', 'en' => 'United Arab Emirates']), 'iso2' => 'AE', 'iso3' => 'AE', 'phone_code' => ''],
            ['id' => 237, 'name' => json_encode(['es' => 'Reino Unido', 'en' => 'United Kingdom']), 'iso2' => 'GB', 'iso3' => 'GB', 'phone_code' => ''],
            ['id' => 238, 'name' => json_encode(['es' => 'Estados Unidos', 'en' => 'United States']), 'iso2' => 'US', 'iso3' => 'US', 'phone_code' => ''],
            ['id' => 239, 'name' => json_encode(['es' => 'United States Minor Outlying Islands', 'en' => 'United States Minor Outlying Islands']), 'iso2' => 'UM', 'iso3' => 'UM', 'phone_code' => ''],
            ['id' => 240, 'name' => json_encode(['es' => 'Uruguay', 'en' => 'Uruguay']), 'iso2' => 'UY', 'iso3' => 'UY', 'phone_code' => ''],
            ['id' => 241, 'name' => json_encode(['es' => 'US Virgin Islands', 'en' => 'US Virgin Islands']), 'iso2' => 'VI', 'iso3' => 'VI', 'phone_code' => ''],
            ['id' => 242, 'name' => json_encode(['es' => 'Uzbekistan', 'en' => 'Uzbekistan']), 'iso2' => 'UZ', 'iso3' => 'UZ', 'phone_code' => ''],
            ['id' => 243, 'name' => json_encode(['es' => 'Vanuatu', 'en' => 'Vanuatu']), 'iso2' => 'VU', 'iso3' => 'VU', 'phone_code' => ''],
            ['id' => 244, 'name' => json_encode(['es' => 'Vatican City', 'en' => 'Vatican City']), 'iso2' => 'VA', 'iso3' => 'VA', 'phone_code' => ''],
            ['id' => 245, 'name' => json_encode(['es' => 'Venezuela', 'en' => 'Venezuela']), 'iso2' => 'VE', 'iso3' => 'VE', 'phone_code' => ''],
            ['id' => 246, 'name' => json_encode(['es' => 'Viet Nam', 'en' => 'Viet Nam']), 'iso2' => 'VN', 'iso3' => 'VN', 'phone_code' => ''],
            ['id' => 247, 'name' => json_encode(['es' => 'Wallis and Futuna', 'en' => 'Wallis and Futuna']), 'iso2' => 'WF', 'iso3' => 'WF', 'phone_code' => ''],
            ['id' => 248, 'name' => json_encode(['es' => 'Western Sahara', 'en' => 'Western Sahara']), 'iso2' => 'EH', 'iso3' => 'EH', 'phone_code' => ''],
            ['id' => 249, 'name' => json_encode(['es' => 'Yemen', 'en' => 'Yemen']), 'iso2' => 'YE', 'iso3' => 'YE', 'phone_code' => ''],
            ['id' => 250, 'name' => json_encode(['es' => 'Zambia', 'en' => 'Zambia']), 'iso2' => 'ZM', 'iso3' => 'ZM', 'phone_code' => ''],
            ['id' => 251, 'name' => json_encode(['es' => 'Zimbabwe', 'en' => 'Zimbabwe']), 'iso2' => 'ZW', 'iso3' => 'ZW', 'phone_code' => ''],
        ];
        Country::upsert($records, ['id'], ['name', 'iso2', 'iso3', 'phone_code']);

        Schema::enableForeignKeyConstraints();
    }

}
